### ISSUE TITLE
DTU polling interval is no longer polled after setting set.

### ISSUE THREAD

**Issue by DanielR92** [hoylabs/OpenDTU-OnBattery#1234] opened 2024-09-06 13:29 UTC
### What happened?

If I set the DTU interval from 5 seconds down to 3 seconds during operation... then I no longer receive any data.
If I restart the DTU, I will receive data again at shorter intervals than set.

### To Reproduce Bug

After a restart, you setup the settings to a new value. The issue will come bag.

### Expected Behavior

After setting the value, the new legal time should be recognized as the maximum.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

gad493c0

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported

**Comment by schlimmchen** [comment] 2024-09-07 19:53
I cannot recall that this ever happened to me, and from looking at the code for 20 min I am confused as to how this could happen at all. I had hoped for an easy explanation.

@spcqike @manos1966 can you guys reproduce this?

**Comment by Manos1966** [comment] 2024-09-07 21:35
Ich werde es morgen testen
(ich habe das DTU interval seit 2023 nicht angefasst 😜 )

**Comment by spcqike** [comment] 2024-09-08 05:51
I can’t. Changing from 1 to 3 to 2 seconds, everything works as expected without reboot.

**Comment by Manos1966** [comment] 2024-09-08 08:08
> git-hash/version of OpenDTU = gad493c0

Welche Version ist diese? Eine ältere?

**Comment by DanielR92** [comment] 2024-09-08 08:18
![grafik](https://github.com/user-attachments/assets/81aaee52-1a24-49bf-a51d-3f0385534b0a)

**Comment by Manos1966** [comment] 2024-09-08 08:22
Aha! Dann macht es also Sinn, warum unsere offizielle Versionen dieses Problem nicht haben.

**Comment by DanielR92** [comment] 2024-09-08 08:26
Ja @schlimmchen hat nach Testern aufgerufen und nun bin ich hier. :)

**Comment by DanielR92** [comment] 2024-09-08 08:28
> I can’t. Changing from 1 to 3 to 2 seconds, everything works as expected without reboot.
You don't understand me correctly, in my version what I have. It is necessary to reboot manually to work with the new settings.

**Comment by schlimmchen** [comment] 2024-09-08 09:00
> Aber diese Seite existiert nicht mehr.

@DanielR92 Das hat damit zu tun, dass ich den commit weggebügelt habe mit einem force push. Damit musst du bitte leben, dass das passieren kann, wenn du Vorabversionen aus Pull Requests installierst.

@spcqike @Manos1966 Thanks for looking into it! Lets keep an eye on it, but it seems this is a fluke. Daniel has multiple of those, but they are real, he showed me by sharing his screen using discord, so there should be something to it...

**Comment by DanielR92** [comment] 2024-09-09 14:45
@schlimmchen Hab doch nichts dagegen gesagt... ;)

**Comment by schlimmchen** [comment] 2024-12-09 19:52
I was in these weeds recently for #1450 and I still don't have any indication of why this should happen. And because of #1450 I also fiddled with the poll interval setting recently. Moreover, I use both the NRF24 and the CMT2300 and both work as expected after adjusting the poll interval. No other person came forward with such an issue. For those reasons, I am going to close this issue now and assume that something specific to Daniel's setup causes the fluke for him.

**Closed by schlimmchen** 2024-12-09 19:52 UTC
Labels: bug
